### ISSUE TITLE
Iosevka Custom Font ?

### ISSUE THREAD

**Issue by leath-dub** [treeman/dotfiles#1]
Hi I am opening an issue as I am wondering what your custom Iosevka font is, I think, unless I am mistaken, it was the one shown in your most recent blog about the T-34 key layout. Any info would be appreciated, ps: I use a ferris as well :>

**Comment by treeman** [comment]
Hi! Sorry for the late response, we've just had a kid and this is the first time I'm opening up GitHub since a month or so.

I do indeed use Iosevka, and I've done some customizations to it. I'm not completely sure, as it was quite a while ago since I did it, but I found a `private-build-plans.toml` with this:

```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-ligation = true

[buildPlans.iosevka-custom.variants.design]
ampersand = "upper-open"
asterisk = "low"
b = "toothless-corner"
capital-g = "toothless"
d = "toothless-corner"
dollar = "open"
g = "doublestorey"
i = "hooky"
l = "serifed-tailed"
lig-ltgteq = "slanted"
m = "earless-corner-double-arch-shortleg"
n = "earless-corner-straight"
nine = "open-contour"
number-sign = "upright"
one = "base"
p = "earless-corner"
percent = "rings-connected"
q = "earless-corner"
six = "open-contour"
u = "toothless-corner"
underscore = "high"
y = "straight-turn"
zero = "slashed"
```

That I hope might be the font I'm using right now?

Please give it a try!

**Comment by leath-dub** [comment]
Hey congrats man ! what a way to start the new year :). Thanks for the response this is most definitely what it is, ill build it later this afternoon to clarify, I am happy to close the issue now though

**Comment by leath-dub** [comment]
Ok so I finally got to building the font, I had to update the build plan as it must have been for an older version the names have changed slightly since, here is the amended build plan if you are interested 
```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-ligation = true

[buildPlans.iosevka-custom.variants.design]
ampersand = "upper-open"
asterisk = "penta-low"
b = "toothless-corner"
capital-g = "toothless-corner-serifless-hooked"
d = "toothless-corner-serifless"
dollar = "open"
g = "double-storey"
i = "hooky"
l = "tailed-serifed"
lig-ltgteq = "slanted"
m = "earless-corner-double-arch-short-leg"
n = "earless-corner-straight"
nine = "open-contour"
number-sign = "upright"
one = "base"
p = "earless-corner"
percent = "rings-continuous-slash-also-connected"
q = "earless-corner"
six = "open-contour"
u = "toothless-corner"
underscore = "high"
y = "straight-turn"
zero = "slashed"
```
